# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - main: ./dojoctl/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X "github.com/zenginedev/dojoctl/runtime.Version={{.Tag}}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - image_templates:
      - zengineDev/dojoctl
brews:
  -
    name: 'dojoctl'
    tap:
      owner: 'zengineDev'
      name: 'homebrew-tap'
    install: |
      bin.install "dojoctl"
